from AllRecipesComScraper import AllRecipes
from FoodComScraper import FoodCom
from PioneerWomanScraper import PioneerWoman
from FoodNetworkComScraper import FoodNetwork
from TwoPeasAndTheirPodScraper import TwoPeas
from MarmitonOrgScraper import Marmiton